version: '2'
services:
  iky_backend:
    container_name: iky_backend
    image: manaattempted/ai-botchat-framework_iky_backend:firsttry
    environment:
      APPLICATION_ENV: Production
    depends_on:
      - mongodb

  iky_gateway:
    container_name: iky_gateway
    image: manaattempted/ai-botchat-framework_iky_gateway:firsttry
    ports:
        - "8088:80"
    depends_on:
      - iky_backend

  mongodb:
    container_name: mongodb
    image: mongo
    hostname: mongodb
    ports:
       - "27017:27017"
    volumes:
      - /home/x3dev/web/bot1.chat12345.com/db:/data 
      - /home/x3dev/web/bot1.chat12345.com/db/configdb:/data/configdb 
      - /home/x3dev/web/bot1.chat12345.com/db/db:/data/db

volumes:
  mongodbdata:
